micronaut:
  application:
    name: space
    type: blocking
  server:
    port: 9595
  security:
    enabled: true
    authentication: bearer
    token:
      bearer:
        enabled: true
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:secret}
              jws-algorithm: HS256
    endpoints:
      login:
        enabled: true
        path: /v1/login
  router:
    static-resources:
      swagger-ui:
        mapping=/swagger-ui/**
        paths=classpath\:META-INF/swagger/views/swagger-ui

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/spacedb`}
    username: ${JDBC_USERNAME:spacedbpguser}
    password: ${JDBC_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES

r2dbc:
  datasources:
    default:
      db-type: postgresql
      driverClassName: io.r2dbc:r2dbc-postgresql
      driver: postgresql
      database: ${R2DBC_DB_NAME:spacedb}
      host: ${R2DBC_DB_HOST:localhost}
      port: ${R2DBC_DB_PORT:5432}
      username: ${JDBC_USERNAME:spacedbpguser}
      password: ${JDBC_PASSWORD:password}
      options:
        autoCommit: true
        maxSize: 10
        protocol: postgres
        initialSize: 5
        maxLifeTime: PT280S
        maxIdleTime: PT60S
        maxAcquireTime: PT6S
        poolName: r2dbc-pool
        registerJmx: true

jooq:
  r2dbc-datasources:
    sql-dialect: POSTGRES

liquibase:
  datasources:
    default:
      enabled: true
      change-log: 'classpath:master.yaml'






