micronaut:
  application:
    name: space
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:secret}
  router:
    static-resources:
      swagger-ui:
        mapping=/swagger-ui/**
        paths=classpath\:META-INF/swagger/views/swagger-ui

datasources:
  default:
    driver-class-name: org.postgresql.Driver

